HR_App/urls.py
from django.urls import path
from HR_App import views

app_name = 'HR_App'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('logs/', views.LogsView.as_view(), name='logs'),
    path('statuspage/', views.UserStatusView.as_view(), name='user_status'),
    path('xceladmin/', views.AdminView.as_view(), name='admin'),
    path('attendance/', views.AttendanceView.as_view(), name='attendance'),
    path('attendance/user/<int:user_id>/', views.UserAttendanceView.as_view(), name='attendance_user'),
    # # functions paths
    # path('on_break/', views.break_start, name='func_break_start'),
    # path('end_break/', views.break_end, name='func_break_end'),
]

TechAdminsProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HR_App.urls')),
]

HR_App/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

from django.utils import timezone


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_year = models.CharField(default=datetime.now().year, max_length=4)
    profile_month = models.CharField(default=datetime.now().month, max_length=2)
    login_time = models.CharField(null=True, blank=True, max_length=200)
    logout_time = models.CharField(null=True, blank=True, max_length=200)
    break_start_time = models.CharField(null=True, blank=True, max_length=200)
    break_end_time = models.CharField(null=True, blank=True, max_length=200)
    total_break_time = models.CharField(default="0:0:0", max_length=200)
    legit_working_time = models.CharField(default="0:0:0", max_length=200)
    is_on_break = models.BooleanField(default=False)
    is_logged_in = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + ' ' + self.profile_year + '-' + self.profile_month


class Logs(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.TimeField(auto_now_add=True)
    date = models.DateField(auto_now_add=True)
    message = models.CharField(max_length=200)

    def __str__(self):
        return self.user.username + ' ' + self.message + ' in', self.time, self.date

class Attendance(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    in_time = models.TimeField(null=True, blank=True)
    out_time = models.TimeField(null=True, blank=True)

    def __str__(self):
        return self.user.username

HR_App/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirm Password')
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class ProfileForm(forms.ModelForm):
    total_break_time = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), disabled=True)
    legit_working_time = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), disabled=True)
    class Meta:
        model = Profile
        fields = '__all__'

HR_App/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import check_password
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, ProfileForm
from .models import Logs, Profile, Attendance, User
import datetime


def create_log(user, message):
    Logs.objects.create(
        user=user,
        time=datetime.datetime.now(),
        message=message
    )


# Create your views here.
class IndexView(TemplateView):
    template_name = 'HR_App/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['profile'] = Profile.objects.get(user=self.request.user)
        return context

    def post(self, request):
        value = request.POST['is_on_break']
        if value == 'break':
            Profile.objects.filter(user=self.request.user).update(
                is_on_break=True,
                break_start_time=datetime.datetime(
                    datetime.datetime.now().year, datetime.datetime.now().month, datetime.datetime.now().day,
                    datetime.datetime.now().hour, datetime.datetime.now().minute, datetime.datetime.now().second
                )
            )
            create_log(self.request.user, 'Started Break')
        else:
            Profile.objects.filter(user=self.request.user).update(
                is_on_break=False,
                break_end_time=datetime.datetime(
                    datetime.datetime.now().year, datetime.datetime.now().month, datetime.datetime.now().day,
                    datetime.datetime.now().hour, datetime.datetime.now().minute, datetime.datetime.now().second
                )
            )
            create_log(self.request.user, f'Ended Break\nTotal Break Time: {self.get_break_duration()}')
            break_duration = self.get_break_duration()
            self.add_break_time(break_duration)
        return redirect('HR_App:index')

    def get_break_duration(self):
        break_start_time = Profile.objects.get(user=self.request.user).break_start_time
        break_end_time = Profile.objects.get(user=self.request.user).break_end_time
        break_start_time = datetime.datetime.strptime(str(break_start_time), '%Y-%m-%d %H:%M:%S')
        break_end_time = datetime.datetime.strptime(str(break_end_time), '%Y-%m-%d %H:%M:%S')
        break_duration = break_end_time - break_start_time
        return break_duration

    def add_break_time(self, time):
        break_time = Profile.objects.get(user=self.request.user).total_break_time
        break_hours = int(break_time.split(':')[0])
        break_minutes = int(break_time.split(':')[1])
        break_seconds = int(break_time.split(':')[2])
        new_time = datetime.timedelta(hours=break_hours, minutes=break_minutes, seconds=break_seconds)
        total_time = new_time + time
        hours, remainder = divmod(total_time.seconds + total_time.days * 24 * 3600, 3600)
        minutes, seconds = divmod(remainder, 60)
        total_time = '{:02d}:{:02d}:{:02d}'.format(hours, minutes, seconds)
        Profile.objects.filter(user=self.request.user).update(total_break_time=total_time)
        print(f"{self.request.user.username} has took a total break time of {total_time}")


class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('HR_App:index')
    template_name = 'HR_App/signup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.on_signup()
        return super().form_valid(form)

    def on_signup(self):
        """
        This function will create a log for the user who just signed up
        :return:
        """
        create_log(self.request.user, 'Signed Up')
        Profile.objects.create(
            user=self.request.user,
            login_time=None,
            logout_time=None,
        )


class LoginView(TemplateView):
    template_name = 'HR_App/login.html'

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            self.on_login()
            return redirect('HR_App:index')
        else:
            return redirect('HR_App:login')

    def on_login(self):
        """
        This function will create a log for the user who just logged in
        :return:
        """
        create_log(self.request.user, 'Logged In')

        Profile.objects.filter(user=self.request.user).update(
            is_on_break=False,
            is_logged_in=True,
            total_break_time='0:0:0',
        )
        year = datetime.datetime.now().year
        month = datetime.datetime.now().month
        day = datetime.datetime.now().day
        hour = datetime.datetime.now().hour
        minute = datetime.datetime.now().minute
        second = datetime.datetime.now().second
        Profile.objects.filter(user=self.request.user).update(
            login_time=datetime.datetime(year, month, day, hour, minute, second),
        )
        att = Attendance.objects.filter(user=self.request.user, date=datetime.datetime.now().date())
        if not att:
            Attendance.objects.create(
                user=self.request.user,
                date=datetime.datetime.now().date(),
                in_time=datetime.datetime(year, month, day, hour, minute, second),
                out_time=datetime.datetime(year, month, day, hour, minute, second),
            )

class LogoutView(LoginRequiredMixin, TemplateView):
    template_name = 'HR_App/logout.html'

    def post(self, request):
        self.on_logout()
        logout(request)
        return redirect('HR_App:login')

    def on_logout(self):
        """
        This function will create a log for the user who just logged out
        :return:
        """
        if Profile.objects.get(user=self.request.user).is_on_break:
            Profile.objects.filter(user=self.request.user).update(
                is_on_break=False,
                break_end_time=datetime.datetime(
                    datetime.datetime.now().year, datetime.datetime.now().month, datetime.datetime.now().day,
                    datetime.datetime.now().hour, datetime.datetime.now().minute, datetime.datetime.now().second
                )
            )
            break_duration = self.get_break_duration()
            self.add_break_time(break_duration)
        year = datetime.datetime.now().year
        month = datetime.datetime.now().month
        day = datetime.datetime.now().day
        hour = datetime.datetime.now().hour
        minute = datetime.datetime.now().minute
        second = datetime.datetime.now().second
        Profile.objects.filter(user=self.request.user).update(
            logout_time=datetime.datetime(year, month, day, hour, minute, second),
            is_on_break=False,
            is_logged_in=False,
        )
        create_log(self.request.user, f'Logged Out\nTotal Duration: {self.get_session_duration()}')
        self.add_worktime(self.get_session_duration())

        att = Attendance.objects.filter(user=self.request.user, date=datetime.datetime.now().date())
        if att:
            att.update(
                out_time=datetime.datetime(year, month, day, hour, minute, second),
            )


    def get_session_duration(self):
        login_time = Profile.objects.get(user=self.request.user).login_time
        logout_time = Profile.objects.get(user=self.request.user).logout_time
        total_break_time = Profile.objects.get(user=self.request.user).total_break_time
        login_time = datetime.datetime.strptime(str(login_time), '%Y-%m-%d %H:%M:%S')
        logout_time = datetime.datetime.strptime(str(logout_time), '%Y-%m-%d %H:%M:%S')
        total_break_time = datetime.datetime.strptime(str(total_break_time), '%H:%M:%S')
        total_break_time = datetime.timedelta(
            hours=total_break_time.hour, minutes=total_break_time.minute, seconds=total_break_time.second
        )
        if login_time and logout_time:
            return (logout_time - login_time) - total_break_time

    def get_break_duration(self):
        break_start_time = Profile.objects.get(user=self.request.user).break_start_time
        break_end_time = Profile.objects.get(user=self.request.user).break_end_time
        break_start_time = datetime.datetime.strptime(str(break_start_time), '%Y-%m-%d %H:%M:%S')
        break_end_time = datetime.datetime.strptime(str(break_end_time), '%Y-%m-%d %H:%M:%S')
        break_duration = break_end_time - break_start_time
        return break_duration

    def add_worktime(self, time):
        worktime = Profile.objects.get(user=self.request.user).legit_working_time
        # total_break_time = Profile.objects.get(user=self.request.user).total_break_time

        workhours = int(worktime.split(':')[0])
        workminutes = int(worktime.split(':')[1])
        workseconds = int(worktime.split(':')[2])

        # total_break_time = datetime.datetime.strptime(str(total_break_time), '%H:%M:%S')
        # total_break_time = datetime.timedelta(
        #     hours=total_break_time.hour, minutes=total_break_time.minute, seconds=total_break_time.second
        # )

        new_time = datetime.timedelta(hours=workhours, minutes=workminutes, seconds=workseconds)
        total_time = new_time + time

        hours, remainder = divmod(total_time.seconds + total_time.days * 24 * 3600, 3600)

templates/HR_App/admin.html
{% extends "HR_App/base.html" %}

{% block title %}Xcel Admin{% endblock %}

{% block content %}
    <h1>Admin Panel</h1>
    <table class="table mt-5 mb-5 text-center table-striped">
        <thead>
            <tr>
                <th>User</th>
                <th>Break Status</th>
            <tr>
        </thead>
        <tbody>
            {% for profile in profiles %}
                {% if not profile.user.is_superuser %}
                <tr>
                    <td><h4>{{ profile.user.username }}</h4></td>
                    <td>
                        {% if profile.is_logged_in %}
                            {% if profile.is_on_break %}
                                <button class="btn btn-danger" onclick="onBreak_on_PanelButtonClick()" data-toggle="modal" data-target="#breakModal{{ profile.id }}">End Break</button>
                            {% else %}
                                <button class="btn btn-success" onclick="onBreak_on_PanelButtonClick()" data-toggle="modal" data-target="#breakModal{{ profile.id }}">Start Break</button>
                            {% endif %}
                        {% else %}
                            Not Logged In
                        {% endif %}
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>

    {% for profile in profiles %}
        {% if not profile.user.is_superuser %}
        <div class="modal fade" id="breakModal{{ profile.id }}" tabindex="-1" role="dialog" aria-labelledby="breakModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="breakModalLabel">Break Setting for {{ profile.user.username }}</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {% if profile.is_on_break %}
                            Do you want to end it's break?
                        {% else %}
                            Do you want to start it's break?
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <form action="" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="profile_id" value="{{ profile.id }}">
                            <input type="hidden" name="is_on_break" value="{{ profile.is_on_break }}">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/HR_App/attendance.html
{% extends "HR_App/base.html" %}

{% block content %}
    <h1>User Attendance</h1>
    <div class="row">
            {% for user in users %}
                <div class="card col-lg-3 col-md-4 col-sm-6 mb-4 p-3 m-2">
                    <div class="card-header">
                        <h2>
                        {{ user.username }}
                        </h2>
                    </div>
                    <div class="card-body">

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'HR_App:attendance_user' user.id %}" class="btn btn-primary">View</a>
                    </div>
                </div>
            {% endfor %}
    </div>


{#    <table class="table">#}
{#        <thead>#}
{#            <tr>#}
{#                <th>User</th>#}
{#                <th>Check In</th>#}
{#                <th>Check Out</th>#}
{#            </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#            {% for user in users %}#}
{#                <tr>#}
{#                    <td>{{ user }}</td>#}
{#                    <td>{{ user.check_in }}</td>#}
{#                    <td>{{ user.check_out }}</td>#}
{#                </tr>#}
{#            {% endfor %}#}
{#        </tbody>#}
{#    </table>#}
{% endblock %}

templates/HR_App/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <!-- Add Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'HR_App:index' %}">Xcel Portal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
          {% if user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'HR_App:admin' %}">Admin</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'HR_App:signup' %}">Create User</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'HR_App:logs' %}">Logs</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'HR_App:user_status' %}">Status</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'HR_App:attendance' %}">Attendance</a>
          {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'HR_App:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'HR_App:login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

<!-- Content -->
<div class="container">
  {% block content %}
  {% endblock %}
</div>

<!-- Add Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<script src="{% static 'HR_App/js/Main.js' %}"></script>

</body>
</html>

templates/HR_App/index.html
{% extends "HR_App/base.html" %}

{% block title %}Xcel Portal{% endblock %}

{% block content %}
    <div class="container">
        <h1>Xcel Portal</h1>
    </div>
    {% if user.is_authenticated %}
        <div class="container">
            <h1><span class="text-primary font-weight-bold text-uppercase mr-2 ml-2">{{ request.user.username }}</span></h1>
        </div>
        {% if profile.is_on_break %}
            <div class="container">
                <h1>You are on break</h1>
            </div>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="is_on_break" value="no_break">
                <button class="btn btn-danger" type="submit">End Break</button>
            </form>
        {% else %}
            <div class="container">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="is_on_break" value="break">
                <button class="btn btn-success" type="submit">Start Break</button>
            </form>
            </div>
        {% endif %}
    {% else %}
        <div class="card text-center mt-5">
            <h1 class="card-header">Welcome to Xcel Portal</h1>
            <a class="btn btn-primary mt-3 mb-3 card-body" href="{% url 'HR_App:login' %}">Login</a>

        </div>
    {% endif %}
{% endblock %}

templates/HR_App/login.html
{% extends "HR_App/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
    <form class="form-group" action="" method="post">
        {% csrf_token %}
        <label class="form-label" for="username">Username</label>
        <input class="form-control" type="text" name="username" id="username">
        <label class="form-label" for="password">Password</label>
        <input class="form-control" type="password" name="password" id="password">
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
{% endblock %}

templates/HR_App/logout.html
{% extends "HR_App/base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
    <h1>Logout</h1>
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Logout</button>
    </form>
{% endblock %}

templates/HR_App/logs.html
{% extends "HR_App/base.html" %}

{% block title %}Logs{% endblock %}

{% block content %}
    <h1>Logs</h1>
    {% if user.is_superuser %}
    <table class="table">
        <thead>
            <tr>
                <th>User</th>
                <th>Message</th>
                <th>Time</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            {% for log in logs %}
                {% if not log.user.is_superuser %}
                    <tr>
                        <td>{{ log.user }}</td>
                        <td>{{ log.message }}</td>
                        <td>{{ log.time }}</td>
                        <td>{{ log.date }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>You are not authorized to view this page.</p>
    {% endif %}
{% endblock %}

templates/HR_App/signup.html
{% extends "HR_App/base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ extra_form.as_p }}
        <button class="btn btn-primary" type="submit">Sign Up</button>
    </form>
{% endblock %}

templates/HR_App/user_attendance.html
{% extends "HR_App/base.html" %}

{% block content %}
    <h1>{{ user_att.first_name }} {{ user_att.last_name }} Attendance</h1>
    <!-- Form for filtering attendance in year, month and day -->

    <section>
        <h2>Filter by:</h2>
        <form action="{% url 'HR_App:attendance_user' user_att.id %}" method="get">
            {% csrf_token %}
            <div class="form-group">
                <label for="year">Year:</label>
                <select class="form-control" id="year" name="year">
                    <option value="">All</option>
                    {% for year in years %}
                        <option value="{{ year }}">{{ year }}</option>
                    {% endfor %}
                </select>
                <label for="month">Month:</label>
                <select class="form-control" id="month" name="month">
                    <option value="">All</option>
                    {% for month in months %}
                        <option value="{{ month }}">{{ month }}</option>
                    {% endfor %}
                </select>
                <label for="day">Day:</label>
                <select class="form-control" id="day" name="day">
                    <option value="">All</option>
                    {% for day in days %}
                        <option value="{{ day }}">{{ day }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Filter</button>
        </form>
    </section>




    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>Date</th>
                <th>Check In</th>
                <th>Check Out</th>
            </tr>
        </thead>
        <tbody>
            {% for att in attendances %}
                <tr>
                    <td>{{ att.date }}</td>
                    <td>{{ att.in_time }}</td>
                    <td>{{ att.out_time }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/HR_App/user_status.html
{% extends "HR_App/base.html" %}

{% block title %}Logs{% endblock %}

{% block content %}
    <h1>Users</h1>
    {% if user.is_superuser %}
    <div class="row">
        {% for profile in profiles %}
            {% if not profile.user.is_superuser %}
                <div class="col-md-4 mt-4">
                        <div class="card text-center">
                            <h2 class="card-header">{{ profile.user.username }}</h2>
                            <p class="card-body">Log Status: {% if profile.is_logged_in %}Logged In{% else %}Logged Out{% endif %}</p>
                            <p class="card-body">Worktime: {{ profile.legit_working_time }}</p>
                            <p class="card-body">
                                Break Status: {% if profile.is_on_break %}On Break{% else %}Not on Break{% endif %}, Total Break this login: {{ profile.total_break_time }}
                            </p>
                        </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <p>You are not authorized to view this page.</p>
    {% endif %}
{% endblock %}